import React from 'react';
import { cn } from '@/app/components/ui/utils';
import { ReportModuleRenderer } from './ReportComponents';

interface Section {
  id: string;
  name: string;
  modules: any[];
}

interface ReportPreviewProps {
  sections: Section[];
  templateName?: string;
}

export const ReportPreview = ({ sections, templateName = "New Template" }: ReportPreviewProps) => {
  return (
    <div className="flex justify-center w-full bg-[#F5F6F8] py-12 min-h-screen overflow-y-auto">
      {/* A4 Page Container */}
      <div className="w-full max-w-[900px] bg-white shadow-lg rounded-lg min-h-[1100px] flex flex-col relative">
        
        {/* 1. REPORT HEADER */}
        <div className="px-12 pt-12 pb-6 border-b-2 border-gray-100">
          <div className="flex justify-between items-start">
            <div className="space-y-1">
              <h1 className="text-2xl font-bold text-gray-900 tracking-tight">Integrated Rack Diagnostic Suite</h1>
              <p className="text-sm font-medium text-gray-500 uppercase tracking-wide">Report Type: Structural Audit</p>
            </div>
            
            <div className="text-right space-y-1">
              <div className="text-sm text-gray-600">
                <span className="font-semibold text-gray-900 w-24 inline-block">Date:</span> 24 Jan 2026
              </div>
              <div className="text-sm text-gray-600">
                <span className="font-semibold text-gray-900 w-24 inline-block">Site:</span> Warehouse A
              </div>
              <div className="text-sm text-gray-600">
                <span className="font-semibold text-gray-900 w-24 inline-block">Template:</span> {templateName}
              </div>
            </div>
          </div>
        </div>

        {/* 2. REPORT BODY */}
        <div className="flex-1 px-12 py-8">
          {sections.length === 0 ? (
            <div className="h-full flex flex-col items-center justify-center text-gray-300 border-2 border-dashed border-gray-100 rounded-lg p-12">
              <p className="text-lg font-medium">No sections added to report.</p>
              <p className="text-sm">Go back to builder to add content.</p>
            </div>
          ) : (
            <div className="space-y-8">
              {sections.map((section, index) => (
                <div key={section.id} className="mt-8 first:mt-0">
                  {/* Section Title */}
                  <div className="flex items-baseline gap-3 mb-6 border-b border-gray-100 pb-2">
                    <span className="text-gray-400 font-bold text-xl">{index + 1}.</span>
                    <h2 className="text-[20px] font-semibold text-gray-900">{section.name}</h2>
                  </div>

                  {/* Section Modules */}
                  <div className="space-y-8 pl-8">
                    {section.modules.length > 0 ? (
                      section.modules.map((module: any) => (
                        <div key={module.instanceId} className="report-module-container">
                          {/* Module Render */}
                          <ReportModuleRenderer module={module} />
                        </div>
                      ))
                    ) : (
                      <p className="text-gray-400 italic text-sm">No modules in this section.</p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* 3. REPORT FOOTER */}
        <div className="px-12 py-8 mt-auto border-t border-gray-100 text-gray-400 text-xs flex justify-between items-center">
          <div>
            <p>Generated by RAMS</p>
            <p>Confidential</p>
          </div>
          <div className="text-right">
            <p>Page 1 of 1</p>
          </div>
        </div>
      </div>
    </div>
  );
};
